-- ============================================
-- Schema SQL cho Quản Lý Đặt Vé Máy Bay
-- Database: Oracle XE
-- User: quanLyDatVeMayBay / 123456
-- ============================================

-- Tạo sequence cho các bảng
CREATE SEQUENCE FLIGHT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TICKET_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USER_ROLE_SEQ START WITH 1 INCREMENT BY 1;

-- Bảng FLIGHT (Chuyến bay)
CREATE TABLE FLIGHT (
    ID              NUMBER PRIMARY KEY,
    FLIGHT_CODE     VARCHAR2(20) NOT NULL UNIQUE,
    AIRLINE         VARCHAR2(100) NOT NULL,
    DEPARTURE_AIRPORT VARCHAR2(100) NOT NULL,
    ARRIVAL_AIRPORT VARCHAR2(100) NOT NULL,
    DEPARTURE_TIME  TIMESTAMP NOT NULL,
    ARRIVAL_TIME    TIMESTAMP NOT NULL,
    TOTAL_SEATS     NUMBER(4) NOT NULL,
    AVAILABLE_SEATS NUMBER(4) NOT NULL,
    PRICE           NUMBER(15,2) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    CREATED_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      NUMBER,
    UPDATED_DATE    TIMESTAMP,
    UPDATED_BY      NUMBER
);

-- Trigger tự động tăng ID cho FLIGHT
CREATE OR REPLACE TRIGGER FLIGHT_TRIGGER
    BEFORE INSERT ON FLIGHT
    FOR EACH ROW
BEGIN
    SELECT FLIGHT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

-- Bảng TICKET (Vé máy bay)
CREATE TABLE TICKET (
    ID           NUMBER PRIMARY KEY,
    FLIGHT_ID    NUMBER NOT NULL,
    SEAT_NUMBER  VARCHAR2(10) NOT NULL,
    TICKET_CLASS VARCHAR2(20) NOT NULL,
    PRICE        NUMBER(15,2) NOT NULL,
    STATUS       VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY   NUMBER,
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY   NUMBER,
    CONSTRAINT FK_TICKET_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID),
    CONSTRAINT UQ_TICKET_SEAT UNIQUE (FLIGHT_ID, SEAT_NUMBER)
);

CREATE OR REPLACE TRIGGER TICKET_TRIGGER
    BEFORE INSERT ON TICKET
    FOR EACH ROW
BEGIN
    SELECT TICKET_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

-- Bảng BOOKING (Đặt vé)
CREATE TABLE BOOKING (
    ID               NUMBER PRIMARY KEY,
    BOOKING_CODE     VARCHAR2(20) NOT NULL UNIQUE,
    TICKET_ID        NUMBER NOT NULL UNIQUE,
    PASSENGER_NAME   VARCHAR2(200) NOT NULL,
    PASSENGER_EMAIL  VARCHAR2(100),
    PASSENGER_PHONE  VARCHAR2(20),
    PASSENGER_ID_CARD VARCHAR2(50),
    BOOKING_DATE     TIMESTAMP NOT NULL,
    STATUS           VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CREATED_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY       NUMBER,
    UPDATED_DATE     TIMESTAMP,
    UPDATED_BY       NUMBER,
    CONSTRAINT FK_BOOKING_TICKET FOREIGN KEY (TICKET_ID) REFERENCES TICKET(ID)
);

CREATE OR REPLACE TRIGGER BOOKING_TRIGGER
    BEFORE INSERT ON BOOKING
    FOR EACH ROW
BEGIN
    SELECT BOOKING_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

-- Bảng USERS (Người dùng)
CREATE TABLE USERS (
    ID           NUMBER PRIMARY KEY,
    USER_NAME    VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD     VARCHAR2(255) NOT NULL,
    FULL_NAME    VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(100),
    SDT          VARCHAR2(20),
    STATUS       NUMBER(1) DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_DATE TIMESTAMP
);

CREATE OR REPLACE TRIGGER USERS_TRIGGER
    BEFORE INSERT ON USERS
    FOR EACH ROW
BEGIN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

-- Bảng ROLE
CREATE TABLE ROLE (
    ROLE_ID     VARCHAR2(50) PRIMARY KEY,
    DESCRIPTION VARCHAR2(200),
    STATUS      NUMBER(1) DEFAULT 1
);

-- Bảng USER_ROLE
CREATE TABLE USER_ROLE (
    ID           NUMBER PRIMARY KEY,
    USER_ID      NUMBER NOT NULL,
    ROLE_ID      VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

CREATE OR REPLACE TRIGGER USER_ROLE_TRIGGER
    BEFORE INSERT ON USER_ROLE
    FOR EACH ROW
BEGIN
    SELECT USER_ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

-- ============================================
-- Dữ liệu mẫu
-- ============================================

-- Roles
INSERT INTO ROLE VALUES ('ADMIN', 'Quản trị viên', 1);
INSERT INTO ROLE VALUES ('USER', 'Người dùng', 1);

-- Admin user (password: admin123 - SHA256 hashed)
-- SHA256("admin123") = 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
INSERT INTO USERS (USER_NAME, PASSWORD, FULL_NAME, EMAIL, STATUS)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Quản Trị Viên', 'admin@example.com', 1);

-- Assign admin role
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
SELECT ID, 'ADMIN' FROM USERS WHERE USER_NAME = 'admin';

-- Sample flights
INSERT INTO FLIGHT (FLIGHT_CODE, AIRLINE, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, AVAILABLE_SEATS, PRICE, STATUS)
VALUES ('VN001', 'Vietnam Airlines', 'Hà Nội (HAN)', 'Hồ Chí Minh (SGN)', TIMESTAMP '2026-04-20 07:00:00', TIMESTAMP '2026-04-20 09:10:00', 150, 150, 1200000, 'SCHEDULED');

INSERT INTO FLIGHT (FLIGHT_CODE, AIRLINE, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, AVAILABLE_SEATS, PRICE, STATUS)
VALUES ('VN002', 'Vietnam Airlines', 'Hồ Chí Minh (SGN)', 'Hà Nội (HAN)', TIMESTAMP '2026-04-20 12:00:00', TIMESTAMP '2026-04-20 14:10:00', 150, 150, 1100000, 'SCHEDULED');

INSERT INTO FLIGHT (FLIGHT_CODE, AIRLINE, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, AVAILABLE_SEATS, PRICE, STATUS)
VALUES ('VJ101', 'VietJet Air', 'Hà Nội (HAN)', 'Đà Nẵng (DAD)', TIMESTAMP '2026-04-21 08:30:00', TIMESTAMP '2026-04-21 09:50:00', 180, 180, 750000, 'SCHEDULED');

INSERT INTO FLIGHT (FLIGHT_CODE, AIRLINE, DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, AVAILABLE_SEATS, PRICE, STATUS)
VALUES ('BB201', 'Bamboo Airways', 'Hà Nội (HAN)', 'Phú Quốc (PQC)', TIMESTAMP '2026-04-22 06:00:00', TIMESTAMP '2026-04-22 08:30:00', 120, 120, 1800000, 'SCHEDULED');

COMMIT;
